config/routes.rb
Rails.application.routes.draw do
 

  resources :cds do
    resources :songs
  end

  root 'cds#index'

end

app/models/cd.rb
class Cd < ActiveRecord::Base
	has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :cd
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cds_controller.rb
class CdsController < ApplicationController
  def index
  	@cds = Cd.all
  end

  def show
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  	@cd=Cd.find(params[:cd_id])
  	@songs = @cd.songs
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/cds/index.html.erb
<table border="1">
<tr>
<td>Album</td>
<td>Artist</td>
<td>Show</td>
</tr>
<% @cds.each do |cd|  %>
<tr>
<td><%= cd.album %></td>
<td><%= cd.artist %></td>
<td><%= link_to "Show Songs", cd_songs_path(cd) %></td>
</tr>
<% end %>
</table>

app/views/cds/show.html.erb
<h1>Cds#show</h1>
<p>Find me in app/views/cds/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CdManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/index.html.erb
<table border="1">
<tr>
<td>Song</td>
<td>Album</td>
<td>Artist</td>
</tr>
<% @songs.each do |song|  %>
<tr>
<td><%= song.songname %></td>
<td><%= song.cd.album %></td>
<td><%= song.cd.artist %></td>
</tr>
<% end %>
</table>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>